### ISSUE TITLE
Accept address lists with a trailing comma

### ISSUE THREAD

**Issue by bradvogel** [jackbearheart/email-addresses#12]
Would be nice if the trailing comma was ignored and this worked:

```
$ npm install email-addresses
npm http GET https://registry.npmjs.org/email-addresses
npm http 304 https://registry.npmjs.org/email-addresses
email-addresses@2.0.1 node_modules/email-addresses
$ node
> var email = require('email-addresses')
undefined
> email.parseAddressList('Kysen Vogel <kysen.vogel@gmail.com>,')
null
```

**Comment by zoellner** [comment]
I know this is an old issue but want to follow up on it.
I think what is needed here is an option to ignore invalid entries and still return the rest of the result.
i.e. `addrs("valid@example.com")` and `addrs("valid@example.com, invalid")` with that switch turned on would both return the same addresses array containing `valid@example.com`

**Comment by jackbearheart** [comment]
Cleaning up some old issues. Can do this with the `partial` option. `addrs({partial: true, input: "valid@example.com, invalid"})`
