### ISSUE TITLE
rejectTLD option for input with no domain part produces error

### ISSUE THREAD

**Issue by pretender** [jackbearheart/email-addresses#33]
Version 3.0.1

addrs = require("email-addresses")
addrs.parseAddressList({input: 'jack@'})
null

addrs.parseAddressList({input: 'jack@', rejectTLD: true})
TypeError: Cannot read property 'semantic' of null
at domainCheckTLD (email-addresses/lib/email-addresses.js:580:27)

**Comment by jackbearheart** [comment]
Thank you for this bug report! This fix should do it. Let me know if you have any other problems.
