### ISSUE TITLE
Release v3.0.2?

### ISSUE THREAD

**Issue by bkemper** [jackbearheart/email-addresses#39]
Hi Jack,

I just bumped into #33.  I saw a fix was merged on Aug 23, 2017, but it was never released.  What can I do to help the release of this patch as v3.0.2?

**Comment by jackbearheart** [comment]
Hey, thanks for asking. I didn't publish since there wasn't much going on at the time. But I'm always happy to publish on request.

I just published 3.0.2 to npm.

Thanks!

**Comment by bkemper** [comment]
@jackbearheart Awesome, thank you very much!!
