### ISSUE TITLE
.git

### ISSUE THREAD

**Issue by xingtongju** [jackbearheart/email-addresses#42]
when i have installed,i found there a .git file in the folder

**Comment by xingtongju** [comment]
version: 3.0.2

**Comment by jackbearheart** [comment]
Hey, thanks for reporting this. Kind of annoying that `npm publish` doesn't ignore the .git file. I published a version (3.0.2-r2) which is exactly the same but without the .git file.

**Comment by gustavnikolaj** [comment]
@jackbearheart Thanks, it did indeed solve the problem.

The problem caused any installation of modules depending on `email-addresses` 3 (any version range except for pinned versions) - among those the `gh-pages` module, if you installed it with npm 3.  npm 3 is still being shipped with node 6 LTS.
