### ISSUE TITLE
`parseOneAddress` sometimes returns `null`

### ISSUE THREAD

**Issue by garyking** [jackbearheart/email-addresses#48]
https://github.com/jackbearheart/email-addresses/blob/03e70bdfb394bc60ed491d97ad908859b6afd9b8/lib/email-addresses.d.ts#L2

I use this package to scan my spam email addresses, and some of them are not legitimate. Like the `From` field would appear as `Example <abc.example.com>`, so the `parseOneAddress` function returns `null`. 

This wasn't indicated in the types. Please add `null` as a possible return type, for the functions for which this is true.

Thanks!

**Comment by jackbearheart** [comment]
I merged some PRs that addressed this today. I haven't cut a new release but this should be fixed. I'll watch out for this going forward. Thank you!
