### ISSUE TITLE
REQUEST: Could the parser get the ".com" or ".net" part of the email in an isolated part property/field name?

### ISSUE THREAD

**Issue by carlosalvidrez** [jackbearheart/email-addresses#56]
Thank you for sharing this work!

A request, hoping you'll consider...
It would be great to also be able to get the .com, .net, .mil, etc.

Not sure it can... but I realize I could be wrong. Could you please let me know?

Thanks!

**Comment by jackbearheart** [comment]
You can get this kind of information in a few ways. It's easy to get the domain, like this:

```
> e.parseOneAddress("carlosalvidrez@example.com").domain;
'example.com'
```

if you want to get the TLD, you could dive further into the parse tree, like this:
```
> e.parseOneAddress("carlosalvidrez@example.com").parts.domain.children[0].children[0].children[1].children[1].children[0].tokens
'.com'
```
Trying playing around with that to see if it has what you like. However, this isn't a particularly great way to access the information, so it's much simpler to chop up the domain:
```
> var domain = e.parseOneAddress("carlosalvidrez@example.com").domain;
> domain.substring(domain.lastIndexOf('.'))
'.com'
```

**Comment by carlosalvidrez** [comment]
Got it, thanks!
