### ISSUE TITLE
Handle unicode names?

### ISSUE THREAD

**Issue by bradvogel** [jackbearheart/email-addresses#8]
I'm getting `null` when trying to parse unicode names:

```
node 
> addrs = require("email-addresses")
> addrs.parseOneAddress('杨孝宇 <xiaoyu@example.com>')
null
```

Are there plans to support it?

**Comment by chieffancypants** [comment]
FYI, it appears as though this only works when using `parseOneAddress`, but still fails if calling the module function directly like so:

```js
import addrs from 'email-addresses';
addrs('"Michał P" <michael.p@example.com>'); // null
```

**Comment by jackbowman** [comment]
@chieffancypants Thanks for the comment.

You're right. The way I implemented this was to add an option implementing RFC 6532 which defaults to `false` but defaults to `true` in the `parseOneAddress` and `parseAddressList` functions. (That was probably a bit strange. My original intent was to have the module function represent a kind of 'pure' RFC 5322, but that may not have as much value as just defaulting to use RFC 6532.)

BTW you can pass a hash with options to the module function and get your desired result like so:
```addrs({input: '"Michał P" <michael.p@example.com>', rfc6532: true});```
